---
- name: Template docker-compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /root/docker-compose.yml
    
- name: Start app service in detached mode
  community.docker.docker_compose_v2:
    project_src: /root
    state: present
